'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Doctor
    Public Property Doctor_Id As String
    Public Property F_name As String
    Public Property L_name As String
    Public Property Phone As Integer
    Public Property email As String
    Public Property patient_list As String

    Public Overridable Property Sessions As ICollection(Of Session) = New HashSet(Of Session)

End Class
