'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Patient
    Public Property Patient_Id As String
    Public Property F_name As String
    Public Property L_name As String
    Public Property Age As Integer
    Public Property Gender As Boolean
    Public Property Phone_number_ As String
    Public Property registration_date As Date
    Public Property demographic As String

    Public Overridable Property Sessions As ICollection(Of Session) = New HashSet(Of Session)

End Class
